### PR TITLE
Feature/docker

### PR DESCRIPTION
**Pull request by stuartMoorhouse**
Dockerfile and entrypoint script for Pipes. Also includes a README for running the Pipes image.

### CODE REVIEW

**Review by sashamitrovich — APPROVED** [review]

**Comment by sashamitrovich** [comment]
Please include '#54' in the merge comment.

**Comment by taatuut** [comment]
README.md says:
`The pull the image: docker push dhfpipes/pipes:v1`

Guess that should be:
`Then pull the image: docker pull dhfpipes/pipes:v1`

Adding -n to The, and changing push in pull. 

However, if I try to pull this results in message `Error response from daemon: manifest for dhfpipes/pipes:v1 not found: manifest unknown: manifest unknown`

So I could not continue testing. Is the image already pushed, or am I missing something else?

**Comment by sashamitrovich** [comment]
What did we say about storing the image in the docker hub? 

I'm against it personally, from the perspective of maintaining it...would only offer self-build image variant. @stuartMoorhouse , @taatuut , what do you think, guys?

**Comment by stuartMoorhouse** [comment]
I'd prefer to have the image in DockerHub, as most users will expect it to be there rather than having to create their own. Can we build the creation of the image into the build?

**Comment by sashamitrovich** [comment]
#54 Instructions how to run Pipes in the docker container

**Pull request merged**
