### PR TITLE
As a developer, I'd like to have a gradle task to build the jar

### PR DESCRIPTION
**Pull request by kghmanuel**
`gradle bootJar` to create the jar file
`gradle runLocal` to run a local copy without creating the jar file

### CODE REVIEW

**Review by sashamitrovich — APPROVED** [review]
Thanks!

**Comment by sashamitrovich** [comment]
Can you also document that, please?

**Comment by kghmanuel** [comment]
With this change, creating the jar file only requires one to issue: `gradle bootJar`. 

For development purposes one would need 2 active command prompts:
1 will run `quasar dev` in project root or `gradle runQuasarDev` on java-middle-tier
1 will run `gradle runLocal` on java-middle-tier.

bulk of these changes focus on converting `buildPackageUiJar` into gradle tasks.

**Review by sashamitrovich — APPROVED** [review]

**Comment by sashamitrovich** [comment]
Please merge, thanks.

**Comment by sashamitrovich** [comment]
Was testing and it's still failing for me on mac.

**Comment by sashamitrovich** [comment]
Tried locally on mac and it works. 
I have a question, though: how to supply command line parameters like ```--deployBackend=true```?

**Comment by sashamitrovich** [comment]
Great work. I think it's ready to merge.

**Comment by sashamitrovich** [comment]
@kghmanuel , would you like to merge it or should I?

**Pull request merged**
